services:
  n1agent:
    image: tecnogera/n1agent:dev   # durante dev local; no CI trocaremos por tags
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env                 # em produção NÃO commitar .env real; usaremos .env no servidor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8001/healthz"]
      interval: 20s
      timeout: 5s
      retries: 5
    # bind só em loopback para o Cloudflare Tunnel enxergar sem expor externamente
    ports:
      - "127.0.0.1:8001:8001"
